Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TradersPortal.Models;
using System.Data.Entity;
using System.Security.Cryptography;
using System.Runtime.InteropServices;
using System.Web.WebPages.Html;
using System.Web.UI.WebControls;
using System.Net;

namespace TradersPortal.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //public ActionResult Index()
        //{



        //    return View();
        //}

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Authorize(Roles = "CanManageTraders")]
        public ActionResult AdminPage()
        {
            return View();
        }




        // GET: Traders
        public ActionResult Index(string searchstate, string searchtrade)
        {
            var traders = db.Traders
                .Include(t => t.Trade)
                .Include(s => s.State).ToList();

            // returns all when all textbox are empty 
            if (string.IsNullOrWhiteSpace(searchstate) && string.IsNullOrWhiteSpace(searchtrade))
            {
                return View(traders);
            }

            // returns traders if trade is selected & state is null
            else if (string.IsNullOrWhiteSpace(searchstate) && !(string.IsNullOrWhiteSpace(searchtrade)))
            {
                return View(db.Traders.Include(t => t.Trade).Include(s => s.State).Where(t => t.Trade.TradeName == searchtrade).ToList());
            }

            // returns traders if state is selected & trade is null
            else if (string.IsNullOrWhiteSpace(searchtrade) && !(string.IsNullOrEmpty(searchstate)))
            {
                return View(db.Traders.Include(t => t.Trade).Include(s => s.State).Where(t => t.State.StateName == searchstate).ToList());
            }

            // returns traders & state if both are selected
            else if (!(string.IsNullOrWhiteSpace(searchtrade) && !(string.IsNullOrEmpty(searchstate))))
            {
                return View(db.Traders.Include(t => t.Trade).Include(s => s.State).Where(s => s.State.StateName == searchstate).Where(t => t.Trade.TradeName == searchtrade).ToList());
            }
            else
            {

                return View(traders);

            }
        }



        public JsonResult AutoCompleteTrade(string prefix)
        {
            var tradelist = (from trade in db.Trades
                             where trade.TradeName.StartsWith(prefix)
                             select new
                             {
                                 label = trade.TradeName,
                                 val = trade.TradeId
                             }).ToList();

            return Json(tradelist);
        }


        public JsonResult AutoCompleteState(string prefix)
        {
            var statelist = (from state in db.States
                             where state.StateName.StartsWith(prefix)
                             select new
                             {
                                 label = state.StateName,
                                 val = state.StateId
                             }).ToList();

            return Json(statelist);
        }


        // GET: Traders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var trader = db.Traders
                .Include(t => t.State)
                .Include(t => t.Trade)
                .Include(s => s.Files)
                .SingleOrDefault(c => c.TraderId == id);


            return View(trader);




        }


    }


  














}

Controllers/StatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TradersPortal.Models;

namespace TradersPortal.Controllers
{
    public class StatesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: States
        public ActionResult Index()
        {
            return View(db.States.ToList());
        }

        // GET: States/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            State state = db.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        // GET: States/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: States/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StateId,StateName")] State state)
        {
            if (ModelState.IsValid)
            {
                db.States.Add(state);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(state);
        }

        // GET: States/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            State state = db.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        // POST: States/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StateId,StateName")] State state)
        {
            if (ModelState.IsValid)
            {
                db.Entry(state).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(state);
        }

        // GET: States/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            State state = db.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        // POST: States/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            State state = db.States.Find(id);
            db.States.Remove(state);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TradersController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TradersPortal.Models;

namespace TradersPortal.Controllers
{
    public class TradersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();




        // GET: Traders

        public ActionResult Index()
        {
            var traders = db.Traders
                .Include(t => t.State)
                .Include(t => t.Trade)
                .ToList();

            return View(traders);
        }


        // GET: Traders
        [Authorize(Roles = "CanManageTraders")]
        public ActionResult IndexAd()
        {
            var traders = db.Traders
                .Include(t => t.State)
                .Include(t => t.Trade)
                .ToList();

            return View(traders);
        }




        // GET: Traders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var trader = db.Traders
                .Include(t => t.State)
                .Include(t => t.Trade)
                .Include(s => s.Files)
                .SingleOrDefault(c => c.TraderId == id);


            return View(trader);




        }









        // GET: Traders/Create
        public ActionResult Create()
        {


            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName");
            ViewBag.TradeId = new SelectList(db.Trades, "TradeId", "TradeName");
            return View();
        }

        // POST: Traders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trader trader, HttpPostedFileBase upload)
        {
         
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };


                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    trader.Files = new List<File> { avatar };
                }
                db.Traders.Add(trader);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");


            }
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName");
            ViewBag.TradeId = new SelectList(db.Trades, "TradeId", "TradeName");
            return View(trader);
          

        }
       
            
            
        




        // GET: Traders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trader trader = db.Traders.Include(s => s.Files).SingleOrDefault(s => s.TraderId == id);
            if (trader == null)
            {
                return HttpNotFound();
            }
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName", trader.StateId);
            ViewBag.TradeId = new SelectList(db.Trades, "TradeId", "TradeName", trader.TradeId);
            return View(trader);
        }

        // POST: Traders/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Trader trader, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                var traderinDb = db.Traders.Include(f => f.Files).Single(c => c.TraderId == trader.TraderId);
                traderinDb.BusinessName = trader.BusinessName;
                traderinDb.ContactFirstName = trader.ContactFirstName;
                traderinDb.ContactLastName = trader.ContactLastName;
                traderinDb.Telephone = trader.Telephone;
                traderinDb.Mobile = trader.Mobile;
                traderinDb.Email = trader.Email;
                traderinDb.RegistrationDate = trader.RegistrationDate;
                traderinDb.TradeId = trader.TradeId;
                traderinDb.StateId = trader.StateId;


                if (upload != null && upload.ContentLength > 0)
                {
                    if (traderinDb.Files.Any(f => f.FileType == FileType.Avatar))
                    {
                        db.Files.Remove(traderinDb.Files.First(f => f.FileType == FileType.Avatar));
                    }
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    traderinDb.Files = new List<File> { avatar };
                }



                db.Entry(traderinDb).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");


        }

        // GET: Traders/Delete/5
        [Authorize(Roles = "CanManageTraders")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var trader = db.Traders.Find(id);
            if (trader == null)
            {
                return HttpNotFound();
            }
            return View(trader);
        }

        // POST: Traders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var trader = db.Traders.Find(id);
            db.Traders.Remove(trader);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TradersPortal.Models;

namespace TradersPortal.Controllers
{
    public class TradesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        // GET: Trades
        public ActionResult Index()
        {
            return View(db.Trades.ToList());
        }

        // GET: Trades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.Trades.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // GET: Trades/Create
        public ActionResult Create()
        {
            return View();
        }



        [ChildActionOnly]
        public ActionResult AddTrade()
        {
            return PartialView("_AddTrade");

        }



        // POST: Trades/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trade trade)
        {
            if (ModelState.IsValid)
            {
                db.Trades.Add(trade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trade);
        }

        // GET: Trades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.Trades.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // POST: Trades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TradeId,TradeName")] Trade trade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trade);
        }

        // GET: Trades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.Trades.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // POST: Trades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trade trade = db.Trades.Find(id);
            db.Trades.Remove(trade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
	ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

<p>Use this area to provide additional information.</p>

Views/Home/AdminPage.cshtml
@{
	ViewBag.Title = "AdminPage";
}

<h2>Admin Page</h2>



<div class="row">
	<div class="col-md-4">



		<div class="jumbotron">
			<input type="button" value="Add Trade" onclick="location.href='@Url.Action("Create", "Trades")'" class="btn btn-primary " />

			<input type="button" value="Trade List" onclick="location.href='@Url.Action("Index", "Trades")'" class="btn btn-primary " />

			@{
				Html.RenderAction("AddTrade", "Trades");
			}



		</div>
	</div>

	<div class="col-md-4">



		<div class="jumbotron">
			<input type="button" value="Register Trader" onclick="location.href='@Url.Action("Create", "Traders")'" class="btn btn-primary " />

			<input type="button" value="Traders List" onclick="location.href='@Url.Action("IndexAd", "Traders")'" class="btn btn-primary " />



		</div>
	</div>

	<div class="col-md-4">



		<div class="jumbotron">
			<input type="button" value="Add User" onclick="location.href='@Url.Action("Create", "Traders")'" class="btn btn-primary " />

			<input type="button" value="Registered Users List" onclick="location.href='@Url.Action("RegisteredUsers", "Account")'" class="btn btn-primary " />



		</div>
	</div>




</div>

<div class="row">
	<div class="col-md-4">
		<div class="jumbotron">
			<input type="button" value="Add State" onclick="location.href='@Url.Action("Create", "States")'" class="btn btn-primary " />

			<input type="button" value="State Lists" onclick="location.href='@Url.Action("Index", "States")'" class="btn btn-primary " />



		</div>
	</div>

	<div class="col-md-4">
	</div>

	<div class="col-md-4">
	</div>

</div>





@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/custom-validator")
}

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model IEnumerable<TradersPortal.Models.Trader>
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<div class="row">
	<div class="col-lg-6">
		<p>Are you a trader? Join us by clicking the button below</p>
		<p>
			<input type="button" value="Join Us" onclick="location.href='@Url.Action("Create", "Traders")'" class="btn btn-primary " />
		</p>
	</div>
	<div class="col-lg-6">
		<p>Click the button to get quotes for a job</p>
		<p>
			<input type="button" value="Get Quote" onclick="location.href='@Url.Action("", "")'" class="btn btn-primary " />
		</p>
	</div>
</div>
<br />
<br />
<br />
<body>
	<div class="jumbotron">
		<p>Use the search tool below to search for Tradesmen</p>
		<p>
			@using (Html.BeginForm("Index", "Home", FormMethod.Get))
			{
				<div class="form-inline">
					<input type="text" name="searchtrade" class="form-control" placeholder="Electrician, Plumber" id="searchtrade" /> <hr/>
					<input type="hidden" id="hfTrade" name="searchtrade" />
					<input type="text" name="searchstate" class="form-control" placeholder="Adamawa, Akwa Ibom" id="searchstate" /> <hr />
					<input type="hidden" id="hfState" name="searchstare" />
					<button class="btn btn-primary">Search</button>
					<br /><br />
				</div>
			}
		</p>
	</div>
</body>
<div class="table-responsive">
	<table class="table table-striped table-hover">
		<tr>
		</tr>
		@foreach (var item in Model)
		{
	<tr>
		<td>
			<img src="~/File?id=@item.Files.First(f => f.FileType == TradersPortal.Models.FileType.Avatar).FileId" alt="avatar" width="100" />
		</td>
	


		<td>
			<div id="width">
				@Html.DisplayFor(modelItem => item.BusinessName)
			</div>
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.State.StateName)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Trade.TradeName)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Telephone)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Mobile)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Email)
		</td>
		<td>
			@*@Html.ActionLink("Edit", "Edit", new { id = item.TraderId }) |*@
			@Html.ActionLink("Details", "Details", new { id = item.TraderId }) @*|
			@Html.ActionLink("Delete", "Delete", new { id = item.TraderId })*@
		</td>
	</tr>
		}
	</table>
</div>
@section scripts
	{
	<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.9.0/themes/smoothness/jquery-ui.css" />
	<script type="text/javascript">
		$(function () {
			$("#searchtrade").autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Home/AutoCompleteTrade/',
						data: " {'prefix' : '" + request.term + "'}",
						dataType: "json",
						type: "POST",
						contentType: "application/json; charset=utf-8",
						success: function (data) {
							response($.map(data, function (item) {
								return item;
							}))
						},
						error: function (response) {
							alert(response.responseText);
						},
						failure: function (response) {
							alert(response.responseText);
						}
					});
				},
				select: function (e, i) {
					$("#hfTrade").val(i.item.val);
				},
				minLength: 0
			});
		});
	</script>
	<script type="text/javascript">
		$(function () {
			$("#searchstate").autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Home/AutoCompleteState/',
						data: " {'prefix' : '" + request.term + "'}",
						dataType: "json",
						type: "POST",
						contentType: "application/json; charset=utf-8",
						success: function (data) {
							response($.map(data, function (item) {
								return item;
							}))
						},
						error: function (response) {
							alert(response.responseText);
						},
						failure: function (response) {
							alert(response.responseText);
						}
					});
				},
				select: function (e, i) {
					$("#hfState").val(i.item.val);
				},
				minLength: 0
			});
		});
	</script>
}
@*<div class="jumbotron">
		<h1>ASP.NET</h1>
		<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
		<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2>Getting started</h2>
			<p>
				ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
				enables a clean separation of concerns and gives you full control over markup
				for enjoyable, agile development.
			</p>
			<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
		</div>
		<div class="col-md-4">
			<h2>Get more libraries</h2>
			<p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
			<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
		</div>
		<div class="col-md-4">
			<h2>Web Hosting</h2>
			<p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
			<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
		</div>
	</div>*@

Views/Home/NIU.cshtml
@model IEnumerable<TradersPortal.Models.Trader>
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<div class="row">
	<div class="col-lg-6">
		<p>Are you a trader? Join us by clicking the button below</p>
		<p>
			<input type="button" value="Join Us" onclick="location.href='@Url.Action("Create", "Traders")'" class="btn btn-primary " />
		</p>
	</div>
	<div class="col-lg-6">
	
	</div>
</div>
<br />
<br />
<br />
<body>
	<div class="jumbotron">
		<p>Use the search tool below to search for Tradesmen</p>
		<p>
			@using (Html.BeginForm("Index", "Home", FormMethod.Get))
			{
				<div class="form-inline">
					<input type="text" name="searchtrade" class="form-control" placeholder="Electrician, Plumber" id="searchtrade" />
					<input type="hidden" id="hfTrade" name="searchtrade" />
					<input type="text" name="searchstate" class="form-control" placeholder="Adamawa, Akwa Ibom" id="searchstate" />
					<input type="hidden" id="hfState" name="searchstare" />
					<button class="btn btn-primary">Search</button>
					<br /><br />
				</div>
			}
		</p>
	</div>
</body>
<div class="table-responsive">
	<table class="table table-striped table-hover">
		<tr>
		</tr>
		@foreach (var item in Model)
		{
	<tr>
		
		<td>
			
				<img src="~/File?id=@item.Files.First(f => f.FileType == TradersPortal.Models.FileType.Avatar).FileId" alt="avatar" width="100" />
			
		</td>
		
		<td>
			<div id="width">
				@Html.DisplayFor(modelItem => item.BusinessName)
			</div>
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.State.StateName)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Trade.TradeName)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Telephone)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Mobile)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Email)
		</td>
		@*<td>
			@Html.ActionLink("Edit", "Edit", new { id = item.TraderId }) |
			@Html.ActionLink("Details", "Details", new { id = item.TraderId }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.TraderId })
		</td>*@
	</tr>
		}
	</table>
</div>
@section scripts
	{
	<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.9.0/themes/smoothness/jquery-ui.css" />
	<script type="text/javascript">
		$(function () {
			$("#searchtrade").autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Home/AutoCompleteTrade/',
						data: " {'prefix' : '" + request.term + "'}",
						dataType: "json",
						type: "POST",
						contentType: "application/json; charset=utf-8",
						success: function (data) {
							response($.map(data, function (item) {
								return item;
							}))
						},
						error: function (response) {
							alert(response.responseText);
						},
						failure: function (response) {
							alert(response.responseText);
						}
					});
				},
				select: function (e, i) {
					$("#hfTrade").val(i.item.val);
				},
				minLength: 0
			});
		});
	</script>
	<script type="text/javascript">
		$(function () {
			$("#searchstate").autocomplete({
				source: function (request, response) {
					$.ajax({
						url: '/Home/AutoCompleteState/',
						data: " {'prefix' : '" + request.term + "'}",
						dataType: "json",
						type: "POST",
						contentType: "application/json; charset=utf-8",
						success: function (data) {
							response($.map(data, function (item) {
								return item;
							}))
						},
						error: function (response) {
							alert(response.responseText);
						},
						failure: function (response) {
							alert(response.responseText);
						}
					});
				},
				select: function (e, i) {
					$("#hfState").val(i.item.val);
				},
				minLength: 0
			});
		});
	</script>
}
@*<div class="jumbotron">
		<h1>ASP.NET</h1>
		<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
		<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2>Getting started</h2>
			<p>
				ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
				enables a clean separation of concerns and gives you full control over markup
				for enjoyable, agile development.
			</p>
			<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
		</div>
		<div class="col-md-4">
			<h2>Get more libraries</h2>
			<p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
			<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
		</div>
		<div class="col-md-4">
			<h2>Web Hosting</h2>
			<p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
			<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
		</div>
	</div>*@